name: Sync with S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA3ZDM7F3NV6M7GVEA
          aws-secret-access-key: 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
          aws-region: eu-north-1

      - name: Sync with S3
        run: aws s3 sync . s3://amazon-s3-newdemo12/
