name: Sync with S3

on:
  push:
    branches:
      - main  # Runs on pushes to main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Install AWS CLI v2
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      # Step 3: Sync repository files to S3
      - name: Sync with S3
        env:
          AWS_ACCESS_KEY_ID: AKIA3ZDM7F3NV6M7GVEA
          AWS_SECRET_ACCESS_KEY: mZHVStCof3SmYlVShl56syQen1NkGUpwOhJfBb3a
          AWS_DEFAULT_REGION: eu-north-1  # Replace with your bucket region if different
        run: |
          aws s3 sync . s3://amazon-s3-newdemo12/ 
